name: Copy To Live

on:
  workflow_run:
    workflows: ["Generate Stable AI Database"]
    types:
      - completed

permissions:
  contents: write
  actions: write

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout nurd branch
        uses: actions/checkout@v4
        with:
          ref: nurd

      - name: Setup Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Fetch and switch to gh-pages
        run: |
          git fetch origin gh-pages
          git checkout gh-pages

      - name: Copy files from nurd
        run: |
          git checkout nurd -- \
            nurd-md5.ai \
            nurd-sha1.ai \
            nurd-sha256.ai \
            database_generation_ci.txt \
            generation_report.html \
            generation_time.html \
            template.html

      - name: Commit and push changes
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git add nurd-md5.ai nurd-sha1.ai nurd-sha256.ai \
                    database_generation_ci.txt generation_report.html generation_time.html template.html
            git commit -m "Auto-update from Generate Stable Database [$(date)]"
            git push origin gh-pages
          else
            echo "⚠️ No changes to commit"
          fi
