name: Generate Index for gh-pages

on:
  push:
    branches: [ gh-pages ]
  workflow_dispatch:

jobs:
  generate-index:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout gh-pages branch
      uses: actions/checkout@v3
      with:
        ref: gh-pages

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Generate index.txt
      run: python generate_index.py

    - name: Commit and push updated index.html
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add index.html
        git commit -m "Update index.html from CI [gh-pages]" || echo "No changes"
        git push

