name: Generate index.html on gh-pages

on:
  push:
    branches: [main]
  workflow_dispatch:
permissions:
  contents: write
jobs:
  generate-index:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout default branch (main)
        uses: actions/checkout@v4
        with:
          path: main

      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install jinja2

      - name: Run generate_index.py
        run: |
          cp main/generate_index.py gh-pages/
          cd gh-pages
          python generate_index.py

      - name: Commit and push updated index.html
        run: |
          cd gh-pages
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add index.html
          git commit -m "Auto-update index.html" || echo "No changes to commit"
          git push
