name: Sign and Deploy

on:
  push:
    branches:
      - unsigned
  workflow_dispatch:

permissions:
  contents: write
  actions: write


jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository (unsigned branch)
        uses: actions/checkout@v4
        with:
          ref: unsigned

      - name: Fetch and Switch to gh-pages branch
        run: |
          git fetch origin gh-pages
          git checkout gh-pages

      - name: Copy Updated Database Files from unsigned
        run: |
          git checkout unsigned -- hypatia-md5-bloom.bin hypatia-sha1-bloom.bin hypatia-sha256-bloom.bin

      - name: Check for Changes
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "GitHub Actions"
            git config user.email "actions@github.com"
            git add hypatia-md5-bloom.bin hypatia-sha1-bloom.bin hypatia-sha256-bloom.bin
            git commit -m "Update database files from unsigned branch [$(date)]"
            git push origin gh-pages
            echo "✅ Files updated and pushed to gh-pages"
          else
            echo "⚠️ No changes to commit"
          fi
