name: Sign and Deploy

on:
  push:
    branches:
      - unsigned
  workflow_dispatch:

permissions:
  contents: write
  actions: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository (unsigned branch)
        uses: actions/checkout@v4
        with:
          ref: unsigned

      - name: Switch to gh-pages branch
        run: |
          git fetch origin gh-pages
          git checkout gh-pages

      - name: Move Updated Database Files
        run: |
          mv ../hypatia-md5-bloom.bin .
          mv ../hypatia-sha1-bloom.bin .
          mv ../hypatia-sha256-bloom.bin .

      - name: Setup Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Commit and Push Changes
        run: |
          git add hypatia-md5-bloom.bin hypatia-sha1-bloom.bin hypatia-sha256-bloom.bin
          git commit -m "Deploy updated database files [$(date)]" || echo "No changes to commit"
          git push origin gh-pages
