name: Sign and Deploy

on:
  push:
    branches:
      - unsigned
  workflow_dispatch:

permissions:
  contents: write
  actions: write

jobs:
  sign:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Import GPG Key
  run: |
    echo "$GPG_PRIVATE_KEY" | base64 --decode | gpg --batch --import
    gpg --list-secret-keys --keyid-format LONG
  env:
    GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}


      - name: Sign File
        run: |
          gpg --local-user 5298C0C0C3E73288 --armor --output hypatia-domains-bloom.bin.sig --detach-sig hypatia-domains-bloom.bin
          echo "✅ File signed using key 5298C0C0C3E73288"

      - name: Debug Signing Result
        run: |
          gpg --verify hypatia-domains-bloom.bin.sig hypatia-domains-bloom.bin

      - name: Checkout gh-pages Branch
        run: |
          git fetch origin gh-pages || git checkout --orphan gh-pages
          git checkout gh-pages
          mkdir -p signed

      - name: Move Signed Files
        run: |
          mv hypatia-domains-bloom.bin signed/
          mv hypatia-domains-bloom.bin.sig signed/

      - name: Configure Git
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"

      - name: Commit and Push
        run: |
          git add .
          git commit -m "Signed file using key 5298C0C0C3E73288"
          git push origin gh-pages

