name: Sign and Deploy

on:
  push:
    branches:
      - unsigned
  workflow_dispatch:

permissions:
  contents: write
  actions: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Switch to gh-pages branch
        run: |
          git fetch origin gh-pages
          git checkout gh-pages

      - name: Copy Updated Database
        run: |
          cp hypatia-domains-bloom.bin ./hypatia-domains-bloom.bin

      - name: Commit and Push Changes
        run: |
          git add hypatia-domains-bloom.bin
          git commit -m "Deploy updated database [$(date)]" || echo "No changes to commit"
          git push origin gh-pages

