name: Sign and Deploy

on:
  workflow_run:
    workflows: ["Generate Stable Database"]
    types:
      - completed

permissions:
  contents: write
  actions: write

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout unsigned branch
        uses: actions/checkout@v4
        with:
          ref: unsigned

      - name: Setup Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Fetch and switch to gh-pages
        run: |
          git fetch origin gh-pages
          git checkout gh-pages

      - name: Copy files from unsigned
        run: |
          git checkout unsigned -- hypatia-md5-bloom.bin hypatia-sha1-bloom.bin hypatia-sha256-bloom.bin

      - name: Commit and push changes
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git add hypatia-md5-bloom.bin hypatia-sha1-bloom.bin hypatia-sha256-bloom.bin
            git commit -m "Auto-update from Generate Stable Database [$(date)]"
            git push origin gh-pages
          else
            echo "⚠️ No changes to commit"
          fi
