name: Sign and Deploy

on:
  push:
    branches:
      - unsigned
  workflow_dispatch:

permissions:
  contents: write
  actions: write

jobs:
  sign-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Debug step to verify branch existence
      - name: Debug Git Branches
        run: |
          git fetch --all
          git branch -a
          git ls-remote --heads origin
      
      - name: Setup Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Checkout gh-pages branch
        run: |
          git checkout gh-pages || git checkout --orphan gh-pages
          
      # Add other signing and deployment steps here

      - name: Push to gh-pages
        run: |
          git add .
          git commit -m "Signed release"
          git push origin gh-pages

